const { z } = require('zod');

/* zod's .url() accepts ANY valid URI scheme, including javascript: and
 * data:text/html. Every URL below ends up in markup or in an attribute at
 * some point, so they all go through this instead, restricted to http and
 * https the same way the tracking URL already was. Reuse this for any new
 * URL field rather than plain .url(). */
const webUrl = (max = 1000) => z.string().url().max(max)
  .refine((u) => /^https?:\/\//i.test(u), 'Must be an http or https URL');

const cartLine = z.object({
  productId: z.string().uuid(),
  size: z.string().min(1).max(20),
  color: z.string().min(1).max(40),
  qty: z.number().int().min(1).max(20),
});

const checkoutSchema = z.object({
  // Generated client side, once, per checkout attempt (not per click). A
  // double-submitted request with the same key returns the order already
  // created for it instead of creating a second one, see routes/orders.js.
  idempotencyKey: z.string().uuid(),
  items: z.array(cartLine).min(1).max(50),
  // A CODE only. The discount itself is never accepted from the client, it
  // is computed server side in src/lib/offers.js.
  offerCode: z.string().trim().max(80).optional().nullable(),
  customer: z.object({
    name: z.string().trim().min(1).max(120),
    email: z.string().trim().email().max(200),
    phone: z.string().trim().regex(/^\d{7,15}$/, 'Enter a valid phone number'),
    address: z.string().trim().min(1).max(300),
    city: z.string().trim().min(1).max(120),
    state: z.string().trim().min(1).max(120),
    pincode: z.string().trim().regex(/^\d{4,8}$/, 'Enter a valid PIN code'),
  }),
});

/* The checkout summary's offer preview. Same cart shape as checkout, minus
 * the customer and the idempotency key, because nothing is created. */
const quoteSchema = z.object({
  items: z.array(cartLine).min(1).max(50),
  offerCode: z.string().trim().max(80).optional().nullable(),
});

const verifyPaymentSchema = z.object({
  orderId: z.string().uuid(),
  razorpayOrderId: z.string().min(1),
  razorpayPaymentId: z.string().min(1),
  razorpaySignature: z.string().min(1),
});

const trackOrderSchema = z.object({
  email: z.string().trim().email().max(200),
  displayId: z.string().trim().min(1).max(40),
});

/* Cancelling from the tracking page proves the same thing order lookup
 * proves: the email on the order plus its display id. */
const cancelOrderSchema = z.object({
  email: z.string().trim().email().max(200),
  displayId: z.string().trim().min(1).max(40),
});

const returnRequestSchema = z.object({
  displayId: z.string().trim().min(1).max(40),
  email: z.string().trim().email().max(200),
  // Exactly which order items, and how many of each, are being returned.
  // The refund amount is never taken from the client, it is computed
  // server side from these items against the order's real recorded
  // prices, see src/lib/returns.js.
  items: z.array(z.object({
    orderItemId: z.string().uuid(),
    quantity: z.number().int().min(1).max(100),
  })).min(1).max(50),
  reason: z.enum(['Wrong size', 'Damaged item', 'Not as described', 'Changed my mind']),
  description: z.string().trim().max(1000).optional().default(''),
  photoUrl: webUrl().optional().nullable(),
});

// The chat session id is generated by the browser and only groups messages
// together. It is never treated as proof of identity, see
// src/middleware/customerAuth.js.
const sessionIdField = z.string().trim().min(8).max(100);

const chatSchema = z.object({
  sessionId: sessionIdField,
  message: z.string().trim().max(1000).optional().default(''),
  // Set when the customer attached a photo through the widget. Checked
  // against this server's own upload host before anything uses it.
  attachmentUrl: z.string().url().max(1000).optional().nullable(),
}).refine((v) => Boolean(v.message) || Boolean(v.attachmentUrl), {
  message: 'Send a message or attach a photo',
});

const requestCodeSchema = z.object({
  sessionId: sessionIdField,
  email: z.string().trim().email().max(200),
  displayId: z.string().trim().min(1).max(40),
});

const verifyCodeSchema = z.object({
  sessionId: sessionIdField,
  code: z.string().trim().regex(/^\d{6}$/, 'Enter the six digit code'),
});

const sessionStateSchema = z.object({ sessionId: sessionIdField });

const pendingActionReviewSchema = z.object({
  note: z.string().trim().max(500).optional().default(''),
});

const adminLoginSchema = z.object({
  email: z.string().trim().email(),
  password: z.string().min(1).max(200),
});

const productUpsertSchema = z.object({
  slug: z.string().trim().min(1).max(80).regex(/^[a-z0-9-]+$/, 'lowercase letters, numbers, and hyphens only'),
  name: z.string().trim().min(1).max(150),
  price: z.number().int().min(0),
  fabric: z.string().trim().max(200).optional().nullable(),
  iconKey: z.string().trim().max(40).optional().default('tee'),
  imageUrl: webUrl().optional().nullable(),
  sizes: z.array(z.string().min(1).max(10)).min(1).max(20),
  colors: z.array(z.object({ name: z.string().min(1).max(40), hex: z.string().regex(/^#[0-9a-fA-F]{6}$/) })).min(1).max(20),
  active: z.boolean().optional().default(true),
});

const orderStatusSchema = z.object({
  status: z.enum(['PENDING_PAYMENT', 'PROCESSING', 'SHIPPED', 'OUT_FOR_DELIVERY', 'DELIVERED', 'CANCELLED']),
  trackingCarrier: z.string().trim().max(80).optional(),
  trackingNumber: z.string().trim().max(80).optional(),
  trackingUrl: z.string().url().max(500).refine((u) => /^https?:\/\//i.test(u), 'Tracking URL must use http or https').optional(),
});

// REFUNDED is deliberately not settable through this schema. It can only be
// reached by POST /api/admin/returns/:id/refund actually succeeding against
// Razorpay, see routes/admin.js, so the label can never be true without a
// real refund having happened.
const returnStatusSchema = z.object({
  status: z.enum(['SUBMITTED', 'APPROVED', 'REJECTED']),
});

const kbUpsertSchema = z.object({
  topic: z.string().trim().min(1).max(150),
  content: z.string().trim().min(1).max(4000),
  active: z.boolean().optional().default(true),
});

const inventoryAdjustSchema = z.object({
  delta: z.number().int().refine((v) => v !== 0, 'delta cannot be zero'),
  reason: z.string().trim().max(300).optional(),
});

const bundleUpsertSchema = z.object({
  title: z.string().trim().min(1).max(150),
  description: z.string().trim().max(1000).default(''),
  productIds: z.array(z.string().uuid()).min(2).max(20),
  active: z.boolean().default(true),
});

const adminUserCreateSchema = z.object({
  name: z.string().trim().min(1).max(120),
  email: z.string().trim().email().max(200),
  password: z.string().min(10).max(200),
  role: z.enum(['operator', 'client']),
});

const widgetSettingsSchema = z.object({
  welcomeMessage: z.string().trim().min(1).max(300),
  suggestedQuestions: z.array(z.string().trim().min(1).max(150)).min(1).max(8),
});

const brandConfigSchema = z.object({
  logoUrl: webUrl().optional().nullable(),
  logoDarkUrl: webUrl().optional().nullable(),
  logoHeight: z.number().int().min(24).max(160).optional(),
  accent: z.string().regex(/^#[0-9a-fA-F]{6}$/).optional(),
  secondary: z.string().regex(/^#[0-9a-fA-F]{6}$/).optional(),
  background: z.string().regex(/^#[0-9a-fA-F]{6}$/).optional(),
  surface: z.string().regex(/^#[0-9a-fA-F]{6}$/).optional(),
  textColor: z.string().regex(/^#[0-9a-fA-F]{6}$/).optional(),
  mutedColor: z.string().regex(/^#[0-9a-fA-F]{6}$/).optional(),
  borderRadius: z.number().int().min(0).max(40).optional(),
  fontFamily: z.string().trim().min(1).max(300).optional(),
  bubbleIcon: z.string().trim().min(1).max(40).optional(),
  widgetPosition: z.enum(['bottom-right', 'bottom-left']).optional(),
  showCart: z.boolean().optional(),
  showTrackOrders: z.boolean().optional(),
});

const offerUpsertSchema = z.object({
  code: z.string().trim().max(80).optional().nullable(),
  title: z.string().trim().min(1).max(150),
  description: z.string().trim().max(1000).default(''),
  kind: z.enum(['PERCENT', 'FLAT', 'FREE_SHIPPING', 'BUNDLE']),
  value: z.number().int().min(0),
  minSubtotal: z.number().int().min(0).default(0),
  productIds: z.array(z.string().uuid()).max(100).default([]),
  active: z.boolean().default(true),
  startsAt: z.string().datetime({ offset: true }).optional().nullable(),
  endsAt: z.string().datetime({ offset: true }).optional().nullable(),
}).superRefine((offer, ctx) => {
  // A PERCENT offer is a percentage, so 9000 is not a big discount, it is a
  // typo that would read as "9000% off" to a customer.
  if (offer.kind === 'PERCENT' && offer.value > 100) {
    ctx.addIssue({ code: 'custom', path: ['value'], message: 'A percentage discount cannot be above 100' });
  }
  // An end date before the start date creates an offer that silently never
  // activates, which looks like a broken agent rather than a bad offer.
  if (offer.startsAt && offer.endsAt && new Date(offer.endsAt) <= new Date(offer.startsAt)) {
    ctx.addIssue({ code: 'custom', path: ['endsAt'], message: 'The end date must be after the start date' });
  }
});


module.exports = {
  checkoutSchema,
  quoteSchema,
  cancelOrderSchema,
  requestCodeSchema,
  verifyCodeSchema,
  sessionStateSchema,
  pendingActionReviewSchema,
  bundleUpsertSchema,
  adminUserCreateSchema,
  verifyPaymentSchema,
  trackOrderSchema,
  returnRequestSchema,
  chatSchema,
  adminLoginSchema,
  productUpsertSchema,
  orderStatusSchema,
  returnStatusSchema,
  kbUpsertSchema,
  inventoryAdjustSchema,
  widgetSettingsSchema,
  brandConfigSchema,
  offerUpsertSchema,
};
